#include "vk_texcompress_bc.h"
#include "vk_shader_module.h"
#include "vk_alloc.h"
#include "vk_pipeline.h"
#include "vk_common_entrypoints.h"
#include "wrapper_private.h"

// This header is generated by Meson from bc_decode.comp
static const uint32_t bc_decode_spv[] = {
#include "bc_decode.spv.h"
};

static VkResult
create_bc_decode_pipeline(struct vk_device *device,
                          struct vk_texcompress_bc_state *state)
{
    VkResult result;
    VkDevice _device = vk_device_to_handle(device);
    const struct vk_device_dispatch_table *disp = &device->dispatch_table;

    // Create Descriptor Set Layout
    const VkDescriptorSetLayoutBinding bindings[] = {
        {
            .binding = 0, // Uniform Buffer for metadata
            .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        },
        {
            .binding = 1, // Storage Buffer for compressed data
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        },
        {
            .binding = 2, // Storage Image for output
            .descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
            .descriptorCount = 1,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
        },
    };

    const VkDescriptorSetLayoutCreateInfo ds_create_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .flags = VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR,
        .bindingCount = ARRAY_SIZE(bindings),
        .pBindings = bindings,
    };

    result = disp->CreateDescriptorSetLayout(_device, &ds_create_info,
                                             state->allocator, &state->ds_layout);
    if (result != VK_SUCCESS)
        return result;

    // Create Pipeline Layout
    // const VkPushConstantRange push_range = {
    //     .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
    //     .offset = 0,
    //     .size = 32, // sizeof our push constant struct in the shader
    // };

    // const VkPipelineLayoutCreateInfo pl_create_info = {
    //     .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
    //     .setLayoutCount = 1,
    //     .pSetLayouts = &state->ds_layout,
    //     .pushConstantRangeCount = 1,
    //     .pPushConstantRanges = &push_range,
    // };
    const VkPipelineLayoutCreateInfo pl_create_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts = &state->ds_layout,
        .pushConstantRangeCount = 0, // MUST be 0 for push descriptors
        .pPushConstantRanges = NULL,
    };

    result = disp->CreatePipelineLayout(_device, &pl_create_info,
                                        state->allocator, &state->pipeline_layout);
    if (result != VK_SUCCESS)
        goto fail_ds_layout;

    // Create Shader Module and Pipeline
    const VkShaderModuleCreateInfo shader_module_create_info = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = sizeof(bc_decode_spv),
        .pCode = bc_decode_spv,
    };

    VkShaderModule shader_module;
    result = disp->CreateShaderModule(_device, &shader_module_create_info,
                                      state->allocator, &shader_module);
    if (result != VK_SUCCESS)
        goto fail_p_layout;

    const VkComputePipelineCreateInfo pipeline_create_info = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .stage = {
            .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage = VK_SHADER_STAGE_COMPUTE_BIT,
            .module = shader_module,
            .pName = "main",
        },
        .layout = state->pipeline_layout,
    };

    result = disp->CreateComputePipelines(_device, state->pipeline_cache, 1,
                                          &pipeline_create_info, state->allocator,
                                          &state->pipeline);

    disp->DestroyShaderModule(_device, shader_module, state->allocator);

    if (result != VK_SUCCESS)
        goto fail_p_layout;

    return VK_SUCCESS;

fail_p_layout:
    disp->DestroyPipelineLayout(_device, state->pipeline_layout, state->allocator);
fail_ds_layout:
    disp->DestroyDescriptorSetLayout(_device, state->ds_layout, state->allocator);
    return result;
}

VkPipeline
vk_texcompress_bc_get_decode_pipeline(struct vk_device *device,
                                      struct vk_texcompress_bc_state *state)
{
    simple_mtx_lock(&state->mutex);

    if (state->pipeline == VK_NULL_HANDLE) {
        create_bc_decode_pipeline(device, state);
    }

    VkPipeline pipeline = state->pipeline;
    simple_mtx_unlock(&state->mutex);
    return pipeline;
}

VkResult
vk_texcompress_bc_init(struct wrapper_device *device,
                       struct vk_texcompress_bc_state **bc_state_out,
                       const VkAllocationCallbacks *allocator,
                       VkPipelineCache pipeline_cache)
{
    struct vk_texcompress_bc_state *state =
        vk_zalloc(&device->vk.alloc, 
            sizeof(struct vk_texcompress_bc_state), 
            alignof(struct vk_texcompress_bc_state), 
            VK_SYSTEM_ALLOCATION_SCOPE_OBJECT);

    if (!state)
        return VK_ERROR_OUT_OF_HOST_MEMORY;

    simple_mtx_init(&state->mutex, mtx_plain);
    state->allocator = allocator;
    state->pipeline_cache = pipeline_cache;

    *bc_state_out = state;
    return VK_SUCCESS;
}

void
vk_texcompress_bc_finish(struct vk_device *device,
                         struct vk_texcompress_bc_state *state)
{
    if (!state) return;

    VkDevice _device = vk_device_to_handle(device);
    const struct vk_device_dispatch_table *disp = &device->dispatch_table;

    if (state->pipeline)
        disp->DestroyPipeline(_device, state->pipeline, state->allocator);
    if (state->pipeline_layout)
        disp->DestroyPipelineLayout(_device, state->pipeline_layout, state->allocator);
    if (state->ds_layout)
        disp->DestroyDescriptorSetLayout(_device, state->ds_layout, state->allocator);

    simple_mtx_destroy(&state->mutex);
    vk_free(state->allocator, state);
}